# Generated by Django 5.2.1 on 2025-05-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='EAN',
            field=models.CharField(default='', max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='ref',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
